# containerd 镜像重定向：registry.k8s.io（K8s 官方镜像）
server = "https://registry.k8s.io"

[host."http://cache-k8s:5000"]
  capabilities = ["pull", "resolve"]

[host."https://k8s.m.daocloud.io"]
  capabilities = ["pull", "resolve"]
